version: "3.9"
services:

  CinemaDB:
    image: postgres:13
    env_file:
      - ./Movie_Service/.env
    volumes:
      - movie-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
  UserDB:
    image: postgres:13
    env_file:
      - ./User_Service/.env
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"
  movie-service:
    build:
      context: ./Movie_Service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./Movie_Service/.env
    ports:
      - "8001:8000"
    volumes:
      - ./Movie_Service:/app
    networks:
      - app-network
    depends_on:
      - CinemaDB


  recommendation-service:
    build:
      context: ./Recommendation_Service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8000"
    volumes:
      - ./Recommendation_Service:/app
    networks:
      - app-network

  review-service:
    build:
      context: ./Review_Service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8003:8000"
    volumes:
      - ./Review_Service:/app
    networks:
      - app-network

  search-service:
    build:
      context: ./Search_Service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8004:8000"
    volumes:
      - ./Search_Service:/app
    networks:
      - app-network

  user-service:
    build:
      context: ./User_Service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8005:8000"
    volumes:
      - ./User_Service:/app
    environment:
      - DATABASE_URL=postgres://postgres:12345@UserDB:5432/UserDB
    networks:
      - app-network
    depends_on:
      - UserDB
    env_file:
      - ./User_Service/.env
    

networks:
  app-network:
    driver: bridge

volumes:
  movie-db-data:
  user-db-data: